apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx-app
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - environment: dev
            namespace: dev
            path: envs/dev
          - environment: qa
            namespace: qa
            path: envs/qa
          - environment: prod
            namespace: prod
            path: envs/prod
  template:
    metadata:
      name: 'nginx-{{environment}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/asa-96/nginx-app'
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      destinationNamespace:
        name: '{{namespace}}'
        createNamespace: true
