apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-qa
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/asa-96/nginx-app'
    targetRevision: HEAD
    path: envs/qa
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: qa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
